# Generated by Django 4.1 on 2025-05-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Type name')),
            ],
            options={
                'db_table': 'tbl_types',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.IntegerField(verbose_name='Login')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('user_status', models.CharField(choices=[('W', 'worker'), ('M', 'master')], default='W', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.IntegerField(verbose_name='User_Login')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Comment')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Done'), (2, 'Rejected')], default=0, verbose_name='Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='stickersapp.types')),
            ],
            options={
                'db_table': 'tbl_requests',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(upload_to='photos/')),
                ('coord_long', models.FloatField(verbose_name='Longitude')),
                ('coord_lat', models.FloatField(verbose_name='Latitude')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stickersapp.requests')),
            ],
            options={
                'db_table': 'tbl_photos',
            },
        ),
    ]
