# Generated by Django 4.1 on 2025-05-21 00:25

from django.db import migrations


def create_initial_types(apps, schema_editor):
    Types = apps.get_model('stickersapp', 'Types')

    Types.objects.create(
        id=5,
        type_name='Здоровье',
    )
    Types.objects.create(
        id=6,
        type_name='Детское',
    )

def create_initial_user(apps, schema_editor):
    Users = apps.get_model('stickersapp', 'Users')

    Users.objects.create(
        login=11111,
        email='main@main.ru',
        password='123456',
        user_status='M'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stickersapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_types),
        migrations.RunPython(create_initial_user),
    ]