# Generated by Django 4.1 on 2025-05-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickersapp', '0002_insert_initial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=255, verbose_name='Last_name'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='Name', max_length=255, verbose_name='Name'),
        ),
    ]
